# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rbatch}
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["fetaro"]
  s.date = %q{2013-01-09}
  s.description = %q{Ruby-based batch framework}
  s.email = %q{fetaro@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.ja.md",
    "README.md"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README.ja.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "doc/rdoc/CHANGELOG.html",
    "doc/rdoc/LICENSE.html",
    "doc/rdoc/RBatch.html",
    "doc/rdoc/RBatch/Cmd.html",
    "doc/rdoc/RBatch/CmdException.html",
    "doc/rdoc/RBatch/CmdResult.html",
    "doc/rdoc/RBatch/Log.html",
    "doc/rdoc/created.rid",
    "doc/rdoc/images/brick.png",
    "doc/rdoc/images/brick_link.png",
    "doc/rdoc/images/bug.png",
    "doc/rdoc/images/bullet_black.png",
    "doc/rdoc/images/bullet_toggle_minus.png",
    "doc/rdoc/images/bullet_toggle_plus.png",
    "doc/rdoc/images/date.png",
    "doc/rdoc/images/find.png",
    "doc/rdoc/images/loadingAnimation.gif",
    "doc/rdoc/images/macFFBgHack.png",
    "doc/rdoc/images/package.png",
    "doc/rdoc/images/page_green.png",
    "doc/rdoc/images/page_white_text.png",
    "doc/rdoc/images/page_white_width.png",
    "doc/rdoc/images/plugin.png",
    "doc/rdoc/images/ruby.png",
    "doc/rdoc/images/tag_green.png",
    "doc/rdoc/images/wrench.png",
    "doc/rdoc/images/wrench_orange.png",
    "doc/rdoc/images/zoom.png",
    "doc/rdoc/index.html",
    "doc/rdoc/js/darkfish.js",
    "doc/rdoc/js/jquery.js",
    "doc/rdoc/js/quicksearch.js",
    "doc/rdoc/js/thickbox-compressed.js",
    "doc/rdoc/lib/rbatch/cmd_rb.html",
    "doc/rdoc/lib/rbatch/config_rb.html",
    "doc/rdoc/lib/rbatch/log_rb.html",
    "doc/rdoc/lib/rbatch_rb.html",
    "doc/rdoc/rdoc.css",
    "lib/rbatch.rb",
    "lib/rbatch/cmd.rb",
    "lib/rbatch/config.rb",
    "lib/rbatch/log.rb",
    "sample/bin/file_batch_copy.rb",
    "sample/bin/openldap_backup.rb",
    "sample/bin/test.rb",
    "sample/config/file_batch_copy.yaml",
    "sample/config/openldap_backup.yaml",
    "sample/config/rbatch.yaml",
    "sample/log/empty",
    "test/cases/test_cmd.rb",
    "test/cases/test_config.rb",
    "test/cases/test_log.rb",
    "test/config/rbatch.yaml",
    "test/mocks/PrintArgs.exe",
    "test/mocks/win_cmd.exe"
  ]
  s.homepage = %q{http://github.com/fetaro/rbatch}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.1}
  s.summary = %q{Ruby-based batch framework}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

